services:
  skysentinel_database:
    image: postgis/postgis:16-3.4
    container_name: skysentinel_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 7yOLjbE0RSa9EJEA14
      POSTGRES_DB: skysentinel_db
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data

  skysentinel_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: skysentinel_api:latest
    container_name: skysentinel_api_container
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  skysentinel_frontend:
    image: node:20
    container_name: skysentinel_ui_container
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"